Added an Ansible role to deploy Syntropy Agent on Oracle Linux.
SyntropyNet/syntropy-ansible-collection pull request #3
Opened 2021-03-30 20:41 UTC by jakubauskas

2021-03-31 07:42 UTC, foxis requested changes
Looks good, however, documentation would greatly benefit visibility of this role.

2021-03-31 07:42 UTC, foxis commented on oracle.yml
> +---
Could you please add this snippet to the README as an example with explanation what it does, requirements, etc?
Preferably there should be a new section called "Ansible Roles" or similar with overview of the roles and this one in particular.

2021-03-31 07:42 UTC, foxis commented on roles/syntropy-oracle/tasks/main.yml
> +    - wireshark
It would be helpful to know the purpose of some of the packages.

2021-03-31 07:42 UTC, foxis commented on roles/syntropy-oracle/vars/main.yml
> +api_key: "{{ '****************************' }}"
README should mention that providing a valid `api_key` variable is mandatory.

2021-03-31 13:27 UTC, jakubauskas commented on roles/syntropy-oracle/vars/main.yml
> +api_key: "{{ '****************************' }}"
Explained about api_key in README file more further.

2021-03-31 13:32 UTC, jakubauskas reviewed
Added required explanations to the README file

2021-03-31 13:32 UTC, jakubauskas commented on oracle.yml
> +---
Added explanation to the README.md file

2021-03-31 15:26 UTC, foxis reviewed
Just last touches to improve grammar and will be good to go.

2021-03-31 15:26 UTC, foxis commented on oracle.yml
> +---
Thanks, now this file could be removed.

2021-03-31 15:26 UTC, foxis commented on roles/syntropy-oracle/README.md
> +This Ansible playbook is for automated installation of Syntropy client for Oracle Linux 8 Distribution. This playbook allows to automatically join connect to Syntropy network.
Probably a mistype, however:
- playbook => role
- "to automatically join connect" => not sure whether to join or connect, but only one should be used

2021-03-31 15:26 UTC, foxis commented on roles/syntropy-oracle/README.md
> +All the network traffic is being handled by Syntropy Agent connections - secure encrypted tunnels based on Wireguard. This network scheme is being managed by Syntropy Platform, which allows easily de
I think that wording for the last sentence could be improved.

2021-03-31 15:26 UTC, foxis commented on roles/syntropy-oracle/README.md
> +Syntropy stack is software which lets you to easily establish VPN connections between remote endpoints, implement network-as-a-code approach and to avoid complex and inefficient network firewall and
Perhaps official Syntropy description would be much better here?

2021-03-31 15:26 UTC, foxis commented on roles/syntropy-oracle/README.md
> +Password: **********lone https://github.com/jpacekajus/syntropy-grafana-prometheus-node-exporter.git
Not sure what happened here, however, I believe that the text after asterisks should be an example of api_key instead of a git command.

2021-04-01 06:25 UTC, foxis approved these changes

2021-04-01 09:01 UTC, merged